// GENERATED by scripts/portrait-assets.mjs — do not edit by hand.
// Re-run `npm run assets` after adding or removing portrait art.
import type { PortraitAssets } from "@/lib/game/portraitAssets";

export const PORTRAIT_ASSETS: Record<string, PortraitAssets> = {
  "/boss/azrael.jpg": {
    depth: "/boss/azrael-depth.png",
    focus: 0.251,
  },
  "/boss/dragor.jpg": {
    depth: "/boss/dragor-depth.png",
    focus: 0.243,
  },
  "/boss/kharon.jpg": {
    depth: "/boss/kharon-depth.png",
    focus: 0.22,
  },
  "/boss/morgeth.jpg": {
    depth: "/boss/morgeth-depth.png",
    focus: 0.365,
  },
  "/boss/nox.jpg": {
    depth: "/boss/nox-depth.png",
    focus: 0.318,
  },
  "/boss/rythen.jpg": {
    depth: "/boss/rythen-depth.png",
    focus: 0.42,
  },
  "/boss/serpina.jpg": {
    depth: "/boss/serpina-depth.png",
    focus: 0.376,
  },
  "/boss/tharos.jpg": {
    depth: "/boss/tharos-depth.png",
    focus: 0.38,
  },
  "/boss/varkos.jpg": {
    depth: "/boss/varkos-depth.png",
    focus: 0.2,
  },
  "/boss/volgaris.jpg": {
    depth: "/boss/volgaris-depth.png",
    focus: 0.451,
  },
  "/hero/classes/guardian.jpg": {
    depth: "/hero/classes/guardian-depth.png",
    focus: 0.2,
  },
  "/hero/classes/merchant.jpg": {
    depth: "/hero/classes/merchant-depth.png",
    focus: 0.451,
  },
  "/hero/classes/shadow.jpg": {
    depth: "/hero/classes/shadow-depth.png",
    focus: 0.455,
  },
  "/hero/classes/warlord.jpg": {
    depth: "/hero/classes/warlord-depth.png",
    focus: 0.553,
  },
};
