/**
 * Scans public/ for the optional companions of every character still — a depth
 * map for the 2.5D parallax, a looping clip for full motion — and writes the
 * result to a generated module the client bundles.
 *
 * The point is that generating art never means editing code: drop
 * `dragor-depth.png` or `dragor.webm` next to `dragor.jpg`, re-run this, and
 * that boss upgrades itself. `prebuild` runs it, so a deploy can never ship a
 * manifest that disagrees with the files beside it.
 *
 *   node scripts/portrait-assets.mjs
 */
import { readdirSync, existsSync, writeFileSync, readFileSync, statSync } from "node:fs";
import { join, dirname, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "src/lib/game/portraitAssets.generated.ts");

/** Directories holding character stills, relative to public/. */
const DIRS = ["boss", "hero/classes"];

/** A still is any image here that is not itself a depth map. */
const STILL_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const DEPTH_EXT = [".png", ".webp", ".jpg"];
const CLIP = [
  ["webm", ".webm"],
  ["mp4", ".mp4"],
];

/**
 * Focal planes measured by make-depth-maps.py when it produced each map. Absent
 * for a hand-authored map, which just falls back to the shader's default.
 */
const FOCUS_FILE = join(root, "scripts/portrait-depth-focus.json");
const focus = existsSync(FOCUS_FILE)
  ? JSON.parse(readFileSync(FOCUS_FILE, "utf8"))
  : {};

const entries = [];

for (const dir of DIRS) {
  const abs = join(root, "public", dir);
  if (!existsSync(abs)) continue;

  for (const file of readdirSync(abs).sort()) {
    const ext = extname(file).toLowerCase();
    const stem = basename(file, ext);
    if (!STILL_EXT.has(ext) || stem.endsWith("-depth")) continue;
    if (!statSync(join(abs, file)).isFile()) continue;

    const found = {};

    for (const dExt of DEPTH_EXT) {
      const name = `${stem}-depth${dExt}`;
      if (existsSync(join(abs, name))) {
        found.depth = `/${dir}/${name}`;
        if (focus[found.depth] !== undefined) found.focus = focus[found.depth];
        break;
      }
    }

    for (const [key, cExt] of CLIP) {
      const name = `${stem}${cExt}`;
      if (existsSync(join(abs, name))) found[key] = `/${dir}/${name}`;
    }

    if (Object.keys(found).length > 0) entries.push([`/${dir}/${file}`, found]);
  }
}

const body = entries.length
  ? entries
      .map(([src, found]) => {
        const fields = Object.entries(found)
          .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
          .join("\n");
        return `  ${JSON.stringify(src)}: {\n${fields}\n  },`;
      })
      .join("\n")
  : "";

writeFileSync(
  OUT,
  `// GENERATED by scripts/portrait-assets.mjs — do not edit by hand.
// Re-run \`npm run assets\` after adding or removing portrait art.
import type { PortraitAssets } from "@/lib/game/portraitAssets";

export const PORTRAIT_ASSETS: Record<string, PortraitAssets> = {${
    body ? `\n${body}\n` : ""
  }};
`,
);

const counts = entries.reduce(
  (acc, [, f]) => {
    if (f.depth) acc.depth++;
    if (f.webm || f.mp4) acc.clip++;
    return acc;
  },
  { depth: 0, clip: 0 },
);

console.log(
  `portrait assets: ${entries.length} enhanced (${counts.depth} depth maps, ${counts.clip} clips) → ${OUT.replace(root + "/", "")}`,
);
